import { useEffect, useState } from 'react';
import api from '../api';

function Empty({ children }) { return <p className="p-6 text-center text-slate-400">{children}</p>; }

export default function AdminPage() {
  const [data, setData] = useState({ listings: [], users: [] }); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [busy, setBusy] = useState('');
  async function loadAdmin() { setLoading(true); setError(''); try { const [listings, users] = await Promise.all([api.get('/admin/listings'), api.get('/admin/users')]); setData({ listings: listings.data, users: users.data }); } catch (err) { setError(err.response?.data?.error || 'Could not load admin data.'); } finally { setLoading(false); } }
  useEffect(() => { loadAdmin(); }, []);
  async function act(path, id) { setBusy(`${path}-${id}`); setError(''); try { await api.put(`/admin/${path}/${id}/${path === 'listings' ? 'flag' : 'deactivate'}`); await loadAdmin(); } catch (err) { setError(err.response?.data?.error || 'Action failed.'); } finally { setBusy(''); } }
  return <div><h1 className="text-3xl font-bold">Admin</h1><p className="mt-1 text-slate-400">Manage listings and member accounts.</p>{error && <p className="mt-5 rounded bg-red-950 p-3 text-sm text-red-300">{error}</p>}{loading ? <p className="mt-6 text-slate-400">Loading admin data...</p> : <div className="mt-6 space-y-8"><section><h2 className="mb-3 text-xl font-semibold">Listings</h2><div className="overflow-x-auto rounded-lg border border-slate-700"><table className="w-full min-w-[650px] text-left text-sm"><thead className="bg-slate-800 text-slate-300"><tr><th className="p-3">Title</th><th className="p-3">Owner</th><th className="p-3">Status</th><th className="p-3">Action</th></tr></thead><tbody>{data.listings.length ? data.listings.map((item) => <tr key={item.id} className="border-t border-slate-700"><td className="p-3">{item.title}</td><td className="p-3 text-slate-400">{item.owner_name}</td><td className="p-3 capitalize">{item.status}</td><td className="p-3">{item.status === 'flagged' ? <span className="text-slate-500">Flagged</span> : <button disabled={busy === `listings-${item.id}`} onClick={() => act('listings', item.id)} className="rounded bg-amber-700 px-3 py-1.5 text-xs disabled:opacity-50">Flag</button>}</td></tr>) : <tr><td colSpan="4"><Empty>No listings found.</Empty></td></tr>}</tbody></table></div></section><section><h2 className="mb-3 text-xl font-semibold">Users</h2><div className="overflow-x-auto rounded-lg border border-slate-700"><table className="w-full min-w-[650px] text-left text-sm"><thead className="bg-slate-800 text-slate-300"><tr><th className="p-3">Name</th><th className="p-3">Email</th><th className="p-3">Role</th><th className="p-3">Account</th><th className="p-3">Action</th></tr></thead><tbody>{data.users.length ? data.users.map((user) => <tr key={user.id} className="border-t border-slate-700"><td className="p-3">{user.name}</td><td className="p-3 text-slate-400">{user.email}</td><td className="p-3 capitalize">{user.role}</td><td className="p-3">{user.is_active ? 'Active' : 'Deactivated'}</td><td className="p-3">{user.is_active ? <button disabled={busy === `users-${user.id}`} onClick={() => act('users', user.id)} className="rounded bg-red-900 px-3 py-1.5 text-xs disabled:opacity-50">Deactivate</button> : <span className="text-slate-500">Inactive</span>}</td></tr>) : <tr><td colSpan="5"><Empty>No users found.</Empty></td></tr>}</tbody></table></div></section></div>}</div>;
}
